config/routes.rb
Rails.application.routes.draw do
  get 'relationships/create'
  get 'relationships/destroy'
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  root to: 'recipes#index'
  resources :recipes do
    collection do
      get 'search'
    end
    resources :comments, only: :create
  end
  resources :notifications, only: :index
  post 'like/:id' => 'likes#create', as: 'create_like'
  delete 'like/:id' => 'likes#destroy', as: 'destroy_like'

  resources :users, only: :show do
    collection do
      get :likes
    end
    member do
      get 'mypege'
    end
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_one_attached :image
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :notifications, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates :price, :body, :image,:material, presence: true
  validates :title, presence: true, length: { maximum: 20 }

  def self.search(search)
    if search != ""
      Recipe.where('title Like(?) OR price Like(?) OR body Like(?) ', "%#{search}%","%#{search}%","%#{search}%")
    else
      Recipe.all
    end
  end

  def create_notification_like!(current_user)
    temp = Notification.where(["visitor_id = ? and visited_id = ? and recipe_id = ? and action = ? ", current_user.id, user_id, id, 'like'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        recipe_id: id,
        visited_id: user_id,
        action: 'like'
      )
      if notification.visitor_id == notification.visited_id
        notification.checked = true
      end
      notification.save if notification.valid?
    end
  end

  def create_notification_comment!(current_user, comment_id)
    temp_ids = Comment.select(:user_id).where(recipe_id: id).where.not(user_id: current_user.id).distinct
    temp_ids.each do |temp_id|
      save_notification_comment!(current_user, comment_id, temp_id['user_id'])
    end
    save_notification_comment!(current_user, comment_id, user_id) if temp_ids.blank?
  end

  def save_notification_comment!(current_user, comment_id, visited_id)
    notification = current_user.active_notifications.new(
      recipe_id: id,
      comment_id: comment_id,
      visited_id: visited_id,
      action: 'comment'
    )
    if notification.visitor_id == notification.visited_id
      notification.checked = true
    end
    notification.save if notification.valid?
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit]
  before_action :set_recipe, only: [:show, :edit, :update, :destroy,]
  before_action :move_to_index, only: [:edit, :update, :destory]
  def index
    @recipes = Recipe.order('created_at DESC')
  end

  def new
    @recipe = Recipe.new
  end

  def create
    recipe = Recipe.new(recipe_params)
    if recipe.save
      redirect_to root_path
    else
      render :new
    end

    def show
      @comments = @recipe.comments.includes(:user)
      @comment = Comment.new
    end
  end

  def edit
  end

  def update
    if @recipe.update(recipe_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    @recipe.destroy
    redirect_to root_path
  end

  def search
    @recipes = Recipe.search(params[:keyword])
  end

  private
  def recipe_params
    params.require(:recipe).permit(:image, :price, :title, :body, :material).merge(user_id: current_user.id)
  end

  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  def move_to_index
    unless @recipe.user_id == current_user.id
      redirect_to action: :index
    end
end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_recipe.html.erb
                  <% if current_user.liked_by?(recipe.id) %>
                    <%= link_to destroy_like_path(recipe), method: :delete, remote: true do %>
                      <%= image_tag "heart.png", class:"iine_im" %>
                    <% end %>
                  <% else %>
                    <%= link_to create_like_path(recipe), method: :post, remote: true  do %>
                      <%= image_tag "hearthi.png", class:"iine_im" %>
                    <% end %>
                  <% end %>
                  <%= recipe.likes.count %>

app/views/recipes/edit.html.erb
<%= render "shared/header" %>

<div class="content_form">
  <h2>レシピ編集</h2>
  <%= form_with(model: @recipe, local: true) do |f| %>
  <div class="content">
    <div id="content_title">
      <div class="content_titles">
        <div class="content_title">
          <h3>・タイトル</h3>
        </div>
        <div class="hissu">
          <p>必須</p>
        </div>
      </div>
        <div class="title_form">
          <%= f.text_area :title, placeholder: "タイトル20字以内",maxlength:"20",class: :hol_ti %>
        </div>
        <div class="ti_co">
          <p>一覧画面に掲載されます。</p>
        </div>
    </div>
    <div class="content_image">
      <div class="co-ims">
        <div class="co_im_te">
          <h3>・写真</h3>
        </div>
        <div class="hissu">
          <p>必須</p>
        </div>
      </div>
      <div class="sho_im sho_im2">
        <%= image_tag @recipe.image ,class: :img %>
      </div>
    <div class="ti_co">
          <p>一覧画面に掲載されます。</p>
        </div>
    <div class="content_recipe">
      <div class="co_res">
        <div class="co_re">
          <h3>・レシピの作り方</h3>
        </div>
        <div class="hissu">
          <p>必須</p>
        </div>
      </div>
      <div class=co_ti>
      <%= f.text_area :body, rows: "7", class: :re_ti_co %>
      </div>
    </div>
    <div class="content_price">
      <div class="co_pr">
        <div class="co_prs">
          <h3>・レシピにかかった金額</h3>
        </div>
        <div class="hissu">
          <p>必須</p>
        </div>
      </div>
      <div class="pr_fo">
        <%= f.text_field :price, placeholder:"例）300",class: :i %><span>円</span>
      </div>
    </div>
    <div class="new_btn">
      <%= f.submit "保存" , class: :tk_btn %>
    </div>
    <% end %>
  </div>
</div>

<%= render "shared/footer" %>

app/views/recipes/index.html.erb
<%= render "shared/header" %>

<%= image_tag("first_views.png", class:"recipe-icon") %>
<div class="new_recipe_body">
  <div class="new_recipe">
    <h2>・・・・新着レシピ・・・・</h2>
  </div>
  <div class="new_body">
    <%= link_to "レシピを投稿する",new_recipe_path,class: :new_recipe_btn %>
  </div>
  <div class="recipe_box">
    <% @recipes.each do |recipe| %>
      <div class="recipe_lists">
        <%= link_to recipe_path(recipe.id), method: :get do %>
          <div class='recipe-img-content'>
            <%= image_tag recipe.image, class: "recipe-img" %>
          </div>
        <% end %>
          <div class='recipe-info'>
            <h3 class='item-name'>
                <%= link_to recipe.user.nickname, "/users/#{recipe.user_id}"  %>
            </h3>
            <div class="title">
            <%= link_to recipe.title,recipe_path(recipe.id), method: :get  %>
            </div>
            <div class='day_iine'>
              <div class='day'>
                <%= l recipe.created_at %>
              </div>
              <div class='iine'>
                <% if user_signed_in? %>
                  <div id="recipe_<%= recipe.id %>">
                    <%= render 'recipe', recipe: recipe %>
                  </div>
                <% else %>
                  <%= image_tag "heart.png", class:"iine_im" %>
                    <%= recipe.likes.count %>
                <% end %>
              </div>
            </div>
          </div>
      </div>
    <% end %>
  </div>
</div>
<%= render "shared/footer" %>

app/views/recipes/new.html.erb
<%= render "shared/header" %>

<div class="content_form">
  <h2>レシピ投稿</h2>
  <%= form_with(model: @recipe, local: true) do |f| %>
  <div class="content">
    <div id="content_title">
      <div class="content_titles">
        <div class="content_title">
          <h3>・タイトル</h3>
        </div>
        <div class="hissu">
          <p>必須</p>
        </div>
      </div>
      <div class="title_form">
        <%= f.text_area :title, placeholder: "タイトル20字以内",maxlength:"20",class: :hol_ti %>
      </div>
      <div class="ti_co">
        <p>一覧画面に掲載されます。</p>
      </div>
    </div>
    <div class="content_image">
      <div class="co-ims">
        <div class="co_im_te">
          <h3>・写真</h3>
        </div>
        <div class="hissu">
          <p>必須</p>
        </div>
      </div>
      <div class="im_fo">
        <div class=im_ti>
          <p>画像を登録</p>
          <%= f.file_field :image,class: :co_im %>
        </div>
      </div>
      <div class="ti_co">
        <p>一覧画面に掲載されます。</p>
      </div>
    </div>
    <div class="content_recipe">
      <div class="co_res">
        <div class="co_re">
          <h3>・材料</h3>
        </div>
        <div class="hissu">
          <p>必須</p>
        </div>
      </div>
      <div class=co_ti>
        <%= f.text_area :material, rows: "7", class: :re_ti_co %>
      </div>
    </div>
    <div class="content_recipe">
      <div class="co_res">
        <div class="co_re">
          <h3>・レシピの作り方</h3>
        </div>
        <div class="hissu">
          <p>必須</p>
        </div>
      </div>
      <div class=co_ti>
        <%= f.text_area :body, rows: "7", class: :re_ti_co %>
      </div>
    </div>
    <div class="content_price">
      <div class="co_pr">
        <div class="co_prs">
          <h3>・レシピにかかった金額</h3>
        </div>
        <div class="hissu">
          <p>必須</p>
        </div>
      </div>
      <div class="pr_fo">
        <%= f.text_field :price, placeholder:"例）300", class: :i %><span>円</span>
      </div>
    </div>
    <div class="new_btn">
      <%= f.submit "投稿" , class: :tk_btn %>
    </div>
  <% end %>
  </div>
</div>

<%= render "shared/footer" %>

app/views/recipes/search.html.erb
<%= render "shared/header" %>

<div class="new_recipe_body">
  <div class="new_recipe">
    <h2>・・・・検索結果・・・・</h2>
  </div>
    <% if user_signed_in? %>
      <div class="new_body">
    <%= link_to "レシピを投稿する",new_recipe_path, class: :new_recipe_btn %>
      </div>
    <%end%>
  <div class="recipe_box">
    <% @recipes.each do |recipe| %>
      <div class="recipe_lists">
        <%= link_to recipe_path(recipe.id), method: :get do %>
          <div class='recipe-img-content'>
            <%= image_tag recipe.image, class: "recipe-img" %>
          </div>
          <div class='recipe-info'>
            <h3 class='item-name'>
              <%= recipe.user.nickname %>
            </h3>
            <div class="title">
              <%= recipe.title %>
            </div>
            <div class='day_iine'>
              <div class='day'>
                <%= l recipe.created_at %>
              </div>
          <% end %>
              <div class='iine'>
                <% if user_signed_in? %>
                  <div id="recipe_<%= recipe.id %>">
                    <%= render 'recipe', recipe: recipe %>
                  </div>
                <% else %>
                  <%= image_tag "heart.png", class:"iine_im" %>
                    <%= recipe.likes.count %>
                <% end %>
              </div>
            </div>
          </div>
      </div>
    <% end %>
  </div>
</div>

<%= render "shared/footer" %>

app/views/recipes/show.html.erb
<%= render "shared/header" %>

<div class="show_body">
  <div class="shw_d">
    <div class="sho_ti">
      <div class="sho_tit">
        <%= @recipe.title  %>
      </div>
      <div class="sho_day">
        <%= l @recipe.created_at%>
      </div>
    </div>
    <div class="sho_im">
      <%= image_tag @recipe.image ,class: :img %>
    </div>
    <div class="sho_bo">
    <div class="sho_aikon">
        <div class="create">
          <P>材料</P>
        </div>
      </div>
      <div class="sho_bos">
        <%= @recipe.material %>
      </div>
      <div class="sho_aikon">
        <div class="create">
          <P>レシピの作り方</P>
        </div>
      </div>
      <div class="sho_bos">
        <%= @recipe.body %>
      </div>
    </div>
    <div class="sho_pr">
      <div class="sho_aikon">
        <div class="create">
          <P>レシピにかかった金額</p>
        </div>
      </div>
      <div class="sho_prs">
        <%= @recipe.price%><span>円</span>
      </div>
    </div>
    <div class="shw_user_name">
        <%= link_to @recipe.user.nickname, "/users/#{@recipe.user_id}"  %>
    </div>
    <div class="sho_syes">
      <div class="sho_sye">
        <h5>この記事をシェアする</h5>
      </div>
      <div class="sye_iine">
        <% if user_signed_in? %>
          <div id="recipe_<%= @recipe.id %>">
            <%= render 'recipe', recipe: @recipe %>
          </div>
        <% else %>
          <%= image_tag "heart.png", class:"iine_im" %>
            <%= @recipe.likes.count %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<% if user_signed_in? %>
<% if  current_user.id != @recipe.user_id  %>

<div class="show_body">
  <div class="shw_d shw_i">
    <div class="sho_t">
      <span>このレシピのコメントや感想を伝えよう！</span>
    </div>
    <div class="comment_form">
      <%= form_with(model: @comment,url: recipe_comments_path(@recipe.id),local: true) do |f| %>
      <div class="commnet_area">
        <div class=comment>
          <%= f.text_area :text ,placeholder: "例)簡単で美味しかったです", class: :com %>
        </div>
        <div class="comment_submit">
          <%= f.submit "感想を送る", class: :sbt_text%>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>
<% else %>
<div class="show_body">
  <div class="shw_d shw_i">
    <div class="sho_t">
      <span>コメント一覧</span>
    </div>
    <% if @recipe.comments.exists? %>
    <ul class="comments_lists">
        <% @recipe.comments.each do |comment| %>
          <li class="comments_list">
            <%= link_to  comment.user.nickname, "/users/#{comment.user_id}", class: :comment_user %>
          </li>
          <li class="comments_text">
            <%= comment.text %>
          </li>
          <li class="comment_time">
            <%= time_ago_in_words(comment.created_at).upcase %><span>前</span>
          </li>
        <% end %>
    </ul>
    <% else %>
        コメントはありません
    <% end %>
  </div>
</div>
<% end %>
<% end %>
<div class="hens_des">
  <% if user_signed_in? %>
    <% if  current_user.id == @recipe.user_id %>
      <div class="hens_body">
        <%= link_to(edit_recipe_path(@recipe.id), method: :get) do %>
          <div class="hens">
            <p>レシピを編集</p>
          </div>
        <% end %>
        <%= link_to(recipe_path(@recipe.id), method: :delete) do %>
          <div class="des">
            <p>削除</p>
        </div>
      <% end %>
    <% else %>
    <% end %>
</div>
  <% end %>

<%= render "shared/footer" %>