config/routes.rb
Rails.application.routes.draw do
  get 'relationships/create'
  get 'relationships/destroy'
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  root to: 'recipes#index'
  resources :recipes do
    collection do
      get 'search'
    end
    resources :comments, only: :create
  end
  resources :notifications, only: :index
  post 'like/:id' => 'likes#create', as: 'create_like'
  delete 'like/:id' => 'likes#destroy', as: 'destroy_like'

  resources :users, only: :show do
    collection do
      get :likes
    end
    member do
      get 'mypege'
    end
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:facebook, :google_oauth2]

  validates :nickname, presence: true, length: { maximum: 7 }
  validates :email, uniqueness: true

  has_many :recipes, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :like_recipes, through: :likes, source: :recipe
  has_many :sns_credentials

  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy
  has_one_attached :avatar

  has_many :following_relationships, foreign_key: "follower_id", class_name: "Relationship",  dependent: :destroy
  has_many :following, through: :following_relationships
  has_many :follower_relationships, foreign_key: "following_id", class_name: "Relationship", dependent: :destroy
  has_many :followers, through: :follower_relationships

  has_many :comments


  def liked_by?(recipe_id)
    likes.where(recipe_id: recipe_id).exists?
  end

  def self.from_omniauth(auth)
    sns = SnsCredential.where(provider: auth.provider, uid: auth.uid).first_or_create
    user = User.where(email: auth.info.email).first_or_initialize(
      nickname: auth.info.name,
      email: auth.info.email
    )
      if user.persisted?
        sns.user = user
        sns.save
      end
      user
  end

  def following?(user)
    following_relationships.find_by(following_id: user.id)
  end

  def follow(user)
    following_relationships.create(following_id: user.id)
  end

  def unfollow(user)
    following_relationships.find_by(following_id: user.id).destroy
  end

  def create_notification_follow!(current_user)
    temp = Notification.where(["visitor_id = ? and visited_id = ? and action = ? ",current_user.id, id, 'follow'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        visited_id: id,
        action: 'follow'
      )
      notification.save if notification.valid?
    end
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    authorization
   end

   def google_oauth2
    authorization
   end

   private

   def authorization
     @user = User.from_omniauth(request.env["omniauth.auth"])
     if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
    else
      render template: 'devise/registrations/new'
    end
   end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:mypage, :follows, :followers]
  before_action :set_user, only: [:show, :edit, :update, :mypege, :follows, :followers,]
  before_action :move_to_index, only: [:mypege]

  def show
  end

  def edit
  end

  def update
  end

  def mypege
  end

  def likes
  end

  def following
    #@userがフォローしているユーザー
    @user  = User.find(params[:id])
    @users = @user.following
    render 'show_follow'
end

def followers
    #@userをフォローしているユーザー
    @user  = User.find(params[:id])
    @users = @user.followers
    render 'show_follower'
end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def move_to_index
    unless current_user.id == @user.id
      redirect_to root_path
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow.html.erb
<%= form_for(current_user, url: relationships_path, method: :post, remote: true) do |f| %>
  <%= hidden_field_tag :following_id, @user.id %>
  <%= f.submit "フォローする", class: "btn btn-outline-secondary" %>
<% end %>

app/views/users/_follow_count.html.erb
<%= @user.following.count %>

app/views/users/_follow_form.html.erb
<% if user_signed_in? && @user != current_user %>
<li>
  <div id="follow_form">
    <% if current_user.following?(@user) %>
      <%= render "unfollow" %>
    <% else %>
      <%= render "follow" %>
    <% end %>
  </div>
  </li>
<% end %>

app/views/users/_follower_count.html.erb
<%= @user.followers.count %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user, url: relationship_path(@user), method: :delete, remote: true) do |f| %>
  <%= f.submit "フォロー解除", class: "btn btn-outline-secondary" %>
<% end %>

app/views/users/_user.html.erb
<div class="recipe_box rebo">
      <% @user.recipes.each do |recipe| %>
        <div class="recipe_lists">
          <%= link_to recipe_path(recipe.id), method: :get do %>
            <div class='recipe-img-content'>
              <%= image_tag recipe.image, class: "recipe-img" %>
            </div>
            <div class='recipe-info'>
              <h3 class='item-name'>
                <%= recipe.user.nickname %>
              </h3>
              <div class="title">
                <%= recipe.title %>
              </div>
              <div class='day_iine'>
                <div class='day'>
                  <%= l recipe.created_at %>
                </div>
            <% end %>
                <div class='iine'>
                  <% if user_signed_in? %>
                <div id="recipe_<%= recipe.id %>">
                    <%= render 'recipes/recipe', recipe: recipe %>
                  </div>
                  <% else %>
                    <%= image_tag "heart.png", class:"iine_im" %>
                      <%= recipe.likes.count %>
                  <% end %>
                </div>
              </div>
            </div>
        </div>
      <% end %>
    </div>
  </div>

app/views/users/followers.html.erb
<%= render "shared/header" %>

<div class="yumy">
  <div class="yuti">
    <div class="yuimti">
      <div class="yuim">
        <% if @user.avatar.attached? %>
          <%= image_tag @user.avatar, class: "recipe-img user_img" %>
        <% else %>
        <%= image_tag("default.png", class: "recipe-img user_img") %>
        <% end %>
      </div>
      <div class="pro">
        <%=link_to followers_user_path(@user.id) do %>
          <div class="frow">
            <h6>フォロワー</h6>
            <div class=frow_in>
              <%= @user.followers.count %>
            </div>
          </div>
        <% end %>
        <%= link_to follows_user_path(@user.id) do %>
          <div class="fro">
            <h6>フォロー</h6>
            <div class=frow_in>
              <%= @user.followings.count %>
            </div>
          </div>
        <% end %>
        <div class="reciin">
          <h6>レシピ数</h6>
          <div class=frow_in>
          <%= @user.recipes.count %>
          </div>
        </div>
      </div>
    </div>
    <div class="yuname"><%= @user.nickname %>さんの情報</div>
    <ul class="yupul">
      <li>
        <i class="fas fa-user"></i>
        <%= link_to "プロフィール"%>
      </li>
      <li>
        <i class="fas fa-arrow-circle-left"></i>
        <%= link_to "戻る", root_path %>
      </li>
    </ul>
  </div>
  <div class="fol_body">
    <div class="fol_ti">
      <P><%= @user.nickname %>さんをフォローしている人（<%= @user.followers.count %>人）</p>
    </div>
    <div class="fol_yu">
      <div class="fol_yu_ti">
      <% @users.each do |user| %>
      <%= link_to user_path(user.id) do %>
      <div class="fol_imgs">
        <div class="fol_img">
          <% if user.avatar.attached? %>
            <%= image_tag user.avatar, class: "recipe-img user_img aicon" %>
          <% else %>
            <%= image_tag("default.png", class: "recipe-img user_img aicon") %>
          <% end %>
        </div>
          <div class="folnames">
            <div class="fol_name">
            <p><%= user.nickname %></p>
          </div>
          <div class="fol">
              <% if current_user != user %>
                <% if user.followed_by?(current_user) %>
                  <p><%=link_to "フォロー解除", user_relationships_path(user.id), method: :delete %></p>
                <% else %>
                  <p><%=link_to "フォローする", user_relationships_path(user.id), method: :post %></p>
                <% end %>
              <% else %>
                <p><%=link_to "マイページへ", "/users/#{current_user.id}/mypege/"%></p>
              <% end %>
            </div>
          </div>
        </div>
          <% end %>
      <% end %>
      </div>
    </div>
  </div>
</div>

<%= render "shared/footer" %>

app/views/users/follows.html.erb
<%= render "shared/header" %>

<div class="yumy">
  <div class="yuti">
    <div class="yuimti">
      <div class="yuim">
        <% if @user.avatar.attached? %>
          <%= image_tag @user.avatar, class: "recipe-img user_img" %>
        <% else %>
        <%= image_tag("default.png", class: "recipe-img user_img") %>
        <% end %>
      </div>
      <div class="pro">
        <%=link_to followers_user_path(@user.id) do %>
          <div class="frow">
            <h6>フォロワー</h6>
            <div class=frow_in>
              <%= @user.followers.count %>
            </div>
          </div>
        <% end %>
        <%= link_to follows_user_path(@user.id) do %>
          <div class="fro">
            <h6>フォロー</h6>
            <div class=frow_in>
              <%= @user.followings.count %>
            </div>
          </div>
        <% end %>
        <div class="reciin">
          <h6>レシピ数</h6>
          <div class=frow_in>
          <%= @user.recipes.count %>
          </div>
        </div>
      </div>
    </div>
    <div class="yuname"><%= @user.nickname %>さんの情報</div>
    <ul class="yupul">
      <li>
        <i class="fas fa-user"></i>
        <%= link_to "プロフィール"%>
      </li>
      <li>
        <i class="fas fa-arrow-circle-left"></i>
        <%= link_to "戻る", root_path %>
      </li>
    </ul>
  </div>
  <div class="fol_body">
    <div class="fol_ti">
      <P><%= @user.nickname %>さんがフォローしている人（<%= @user.followings.count %>人）</p>
    </div>
    <div class="fol_yu">
      <div class="fol_yu_ti">
      <% @users.each do |user| %>
      <%= link_to user_path(user.id) do %>
      <div class="fol_imgs">
        <div class="fol_img">
          <% if user.avatar.attached? %>
            <%= image_tag user.avatar, class: "recipe-img user_img aicon" %>
          <% else %>
            <%= image_tag("default.png", class: "recipe-img user_img aicon") %>
          <% end %>
        </div>
          <div class="folnames">
            <div class="fol_name">
            <p><%= user.nickname %></p>
          </div>
          <div class="fol">
              <% if current_user != user %>
                <% if user.followed_by?(current_user) %>
                  <p><%=link_to "フォロー解除", user_relationships_path(user.id), method: :delete %></p>
                <% else %>
                  <p><%=link_to "フォローする", user_relationships_path(user.id), method: :post %></p>
                <% end %>
              <% else %>
                <p><%=link_to "マイページへ", "/users/#{current_user.id}/mypege/"%></p>
              <% end %>
            </div>
          </div>
        </div>
          <% end %>
      <% end %>
      </div>
    </div>
  </div>
</div>

<%= render "shared/footer" %>

app/views/users/likes.html.erb
<%= render "shared/header" %>

<div class="new_recipe iine_list">
    <h2>・・・・お気に入りレシピ一覧・・・・</h2>
  </div>

<div class="yumy">
  <div class="yuti">
    <div class="yuimti">
      <div class="yuim">
        <% if current_user.avatar.attached? %>
          <%= image_tag current_user.avatar, class: "recipe-img user_img" %>
        <% else %>
        <%= image_tag("default.png", class: "recipe-img user_img") %>
        <% end %>
      </div>
      <div class="pro">
        <%=link_to followers_user_path(current_user) do %>
          <div class="frow">
            <h6>フォロワー</h6>
            <div class=frow_in>
              <%= current_user.followers.count %>
            </div>
          </div>
        <% end %>
        <%= link_to following_user_path(current_user) do %>
          <div class="fro">
            <h6>フォロー</h6>
            <div class=frow_in>
              <%= current_user.following.count %>
            </div>
          </div>
        <% end %>
        <div class="reciin">
          <h6>レシピ数</h6>
          <div class=frow_in>
          <%= current_user.recipes.count %>
          </div>
        </div>
      </div>
    </div>
    <div class="yuname"><%= current_user.nickname %>さんのメニュー</div>
    <ul class="yupul">
      <li>
        <i class="fas fa-user"></i>
        <%= link_to "会員情報変更",edit_user_registration_path %>
      </li>
      <li>
        <i class="fas fa-arrow-circle-left"></i>
        <%= link_to "戻る", :back %>
      </li>
    </ul>
  </div>

  <div class="recipe_box rebo">
      <% current_user.like_recipes.each do |recipe| %>
        <div class="recipe_lists">
          <%= link_to recipe_path(recipe.id), method: :get do %>
            <div class='recipe-img-content'>
              <%= image_tag recipe.image, class: "recipe-img" %>
            </div>
            <div class='recipe-info'>
              <h3 class='item-name'>
                <%= recipe.user.nickname %>
              </h3>
              <div class="title">
                <%= recipe.title %>
              </div>
              <div class='day_iine'>
                <div class='day'>
                  <%= l recipe.created_at %>
                </div>
            <% end %>
                <div class='iine'>
                  <% if user_signed_in? %>
                <div id="recipe_<%= recipe.id %>">
                    <%= render 'recipes/recipe', recipe: recipe %>
                  </div>
                  <% else %>
                    <%= image_tag "heart.png", class:"iine_im" %>
                      <%= recipe.likes.count %>
                  <% end %>
                </div>
              </div>
            </div>
        </div>
      <% end %>
    </div>
  </div>
</div>
<%= render "shared/footer" %>

app/views/users/mypege.html.erb
<%= render "shared/header" %>
<div class="new_recipe iine_list">
    <h2>・・・・<%= @user.nickname %>さんのマイページ・・・・</h2>
  </div>
<div class="yumy">
  <div class="yuti">
    <div class="yuimti">
      <div class="yuim">
        <% if @user.avatar.attached? %>
          <%= image_tag @user.avatar, class: "recipe-img user_img" %>
        <% else %>
          <%= image_tag("default.png", class: "recipe-img user_img") %>
        <% end %>
      </div>
      <div class="pro">
        <%=link_to followers_user_path(@user.id) do %>
          <div class="frow">
            <h6>フォロワー</h6>
            <div class=frow_in>
              <%= @user.followers.count %>
            </div>
          </div>
        <% end %>
        <%= link_to  following_user_path(@user.id) do %>
          <div class="fro">
            <h6>フォロー</h6>
            <div class=frow_in>
              <%= @user.following.count %>
            </div>
          </div>
        <% end %>
        <div class="reciin">
          <h6>レシピ数</h6>
          <div class=frow_in>
          <%= @user.recipes.count %>
          </div>
        </div>
      </div>
    </div>
    <div class="yuname"><%= @user.nickname %>さんのメニュー</div>
    <ul class="yupul">
      <li>
        <i class="fas fa-user"></i>
        <%= link_to "会員情報変更",edit_user_registration_path %>
      </li>
      <li>
        <i class="fab fa-gratipay"></i>
        <%= link_to "お気に入りレシピ", likes_users_path %>
      </li>
      <li>
        <i class="fas fa-arrow-circle-left"></i>
        <%= link_to "戻る",:back %>
      </li>
    </ul>
  </div>
    <%= render partial: 'user', locals: { user: @user } %>
</div>
<%= render "shared/footer" %>

app/views/users/show.html.erb
<%= render "shared/header" %>
 <div class=yu_ti>
    <%= @user.nickname %>さんのマイレシピ一覧
</div>
<div class="yumy">
  <div class="yuti">
    <div class="yuimti">
      <div class="yuim">
        <% if @user.avatar.attached? %>
          <%= image_tag @user.avatar, class: "recipe-img user_img" %>
        <% else %>
        <%= image_tag("default.png", class: "recipe-img user_img") %>
        <% end %>
      </div>
      <div class="pro">
        <%=link_to followers_user_path(@user.id) do %>
          <div class="frow follower">
          <h6>フォロワー</h6>
            <div class=frow_in id='follower-count'>
              <%= render 'follower_count' %>
            </div>
          </div>
        <% end %>
        <%= link_to following_user_path(@user.id) do %>
          <div class="fro follow">
            <h6>フォロー</h6>
            <div class="frow_in" id="follow-count">
              <%= render 'follow_count' %>
            </div>
          </div>
        <% end %>
        <div class="reciin">
          <h6>レシピ数</h6>
          <div class=frow_in>
          <%= @user.recipes.count %>
          </div>
        </div>
      </div>
    </div>
    <div class="yuname"><%= @user.nickname %>さんの情報</div>
    <ul class="yupul">
      <li>
        <i class="fas fa-user"></i>
        <%= link_to "プロフィール"%>
      </li>
        <%= render "follow_form" %>
      <li>
        <i class="fas fa-arrow-circle-left"></i>
        <%= link_to "戻る", :back %>
      </li>
    </ul>
  </div>
  <%= render partial: 'user', locals: { user: @user } %>
</div>


<%= render "shared/footer" %>

app/views/users/show_follow.html.erb
<%= render "shared/header" %>

<div class="yumy">
  <div class="yuti">
    <div class="yuimti">
      <div class="yuim">
        <% if @user.avatar.attached? %>
          <%= image_tag @user.avatar, class: "recipe-img user_img" %>
        <% else %>
        <%= image_tag("default.png", class: "recipe-img user_img") %>
        <% end %>
      </div>
      <div class="pro">
        <%=link_to followers_user_path(@user.id) do %>
          <div class="frow">
            <h6>フォロワー</h6>
            <div class=frow_in>
              <%= @user.followers.count %>
            </div>
          </div>
        <% end %>
        <%= link_to  following_user_path(@user.id) do %>
          <div class="fro">
            <h6>フォロー</h6>
            <div class=frow_in>
              <%= @user.following.count %>
            </div>
          </div>
        <% end %>
        <div class="reciin">
          <h6>レシピ数</h6>
          <div class=frow_in>
          <%= @user.recipes.count %>
          </div>
        </div>
      </div>
    </div>
    <div class="yuname"><%= @user.nickname %>さんの情報</div>
    <ul class="yupul">
      <li>
        <i class="fas fa-user"></i>
        <%= link_to "プロフィール"%>
      </li>
      <li>
        <i class="fas fa-arrow-circle-left"></i>
        <%= link_to "戻る", :back %>
      </li>
    </ul>
  </div>
  <div class="fol_body">
    <div class="fol_ti">
      <P><%= @user.nickname %>さんがフォローしている人（<%= @user.following.count %>人）</p>
    </div>
    <div class="fol_yu">
      <div class="fol_yu_ti">
      <% @users.each do |user| %>
      <%= link_to user_path(user.id) do %>
      <div class="fol_imgs">
        <div class="fol_img">
          <% if user.avatar.attached? %>
            <%= image_tag user.avatar, class: "recipe-img user_img aicon" %>
          <% else %>
            <%= image_tag("default.png", class: "recipe-img user_img aicon") %>
          <% end %>
        </div>
          <div class="folnames">
            <div class="fol_name">
            <p><%= user.nickname %></p>
          </div>
          </div>
        </div>
          <% end %>
      <% end %>
      </div>
    </div>
  </div>
</div>

<%= render "shared/footer" %>

app/views/users/show_follower.html.erb
<%= render "shared/header" %>

<div class="yumy">
  <div class="yuti">
    <div class="yuimti">
      <div class="yuim">
        <% if @user.avatar.attached? %>
          <%= image_tag @user.avatar, class: "recipe-img user_img" %>
        <% else %>
        <%= image_tag("default.png", class: "recipe-img user_img") %>
        <% end %>
      </div>
      <div class="pro">
        <%=link_to followers_user_path(@user.id) do %>
          <div class="frow">
            <h6>フォロワー</h6>
            <div class=frow_in>
              <%= @user.followers.count %>
            </div>
          </div>
        <% end %>
        <%= link_to following_user_path(@user.id) do %>
          <div class="fro">
            <h6>フォロー</h6>
            <div class=frow_in>
              <%= @user.following.count %>
            </div>
          </div>
        <% end %>
        <div class="reciin">
          <h6>レシピ数</h6>
          <div class=frow_in>
          <%= @user.recipes.count %>
          </div>
        </div>
      </div>
    </div>
    <div class="yuname"><%= @user.nickname %>さんの情報</div>
    <ul class="yupul">
      <li>
        <i class="fas fa-user"></i>
        <%= link_to "プロフィール"%>
      </li>
      <li>
        <i class="fas fa-arrow-circle-left"></i>
        <%= link_to "戻る", :back %>
      </li>
    </ul>
  </div>
  <div class="fol_body">
    <div class="fol_ti">
      <P><%= @user.nickname %>さんをフォローしている人（<%= @user.followers.count %>人）</p>
    </div>
    <div class="fol_yu">
      <div class="fol_yu_ti">
      <% @users.each do |user| %>
      <%= link_to user_path(user.id) do %>
      <div class="fol_imgs">
        <div class="fol_img">
          <% if user.avatar.attached? %>
            <%= image_tag user.avatar, class: "recipe-img user_img aicon" %>
          <% else %>
            <%= image_tag("default.png", class: "recipe-img user_img aicon") %>
          <% end %>
        </div>
          <div class="folnames">
            <div class="fol_name">
            <p><%= user.nickname %></p>
          </div>
          </div>
        </div>
          <% end %>
      <% end %>
      </div>
    </div>
  </div>
</div>

<%= render "shared/footer" %>