config/routes.rb
Rails.application.routes.draw do
  get 'relationships/create'
  get 'relationships/destroy'
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  root to: 'recipes#index'
  resources :recipes do
    collection do
      get 'search'
    end
    resources :comments, only: :create
  end
  resources :notifications, only: :index
  post 'like/:id' => 'likes#create', as: 'create_like'
  delete 'like/:id' => 'likes#destroy', as: 'destroy_like'

  resources :users, only: :show do
    collection do
      get :likes
    end
    member do
      get 'mypege'
    end
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
end

app/views/shared/_footer.html.erb
<footer class="footer_body">
  <div class="o_menu">
    <div class="menu">
      <div class=fo_se>
        <div class="re_se">
          <h5>レシピをさがす</h5>
        </div>
        <ul class="re_me">
          <li>-カテゴリー</li>
          <li>-話題のレシピ</li>
          <li>-人気の検索キーワード</li>
          <%= link_to("/") do %>
            <li>-新着レシピ</li>
          <% end %>
        </ul>
      </div>
      <div class="re_ka">
        <div class="re_ki">
          <h5>レシピを書く</h5>
        </div>
        <ul class="re_ka_me">
          <li><%= link_to"-レシピを書く",new_recipe_path %></li>
          <li>-レシピの書き方について</li>
        </ul>
      </div>
      <div class="osu">
        <div class="osu_ti">
          <h5>おすすめ</h5>
        </div>
        <ul class="osu_me">
          <li>-モバイルサービス</li>
          <li>-ニュース</li>
      </div>
      <div class="my">
        <div class="my_ti">
        <% if user_signed_in? %>
          <%= link_to "/users/#{current_user.id}/mypege/" do %>
            <h5>あなたのページ</h5>
          <% end %>
        <% end %>
        </div>
        <ul class="my_me">
          <li><%= link_to "-ユーザー登録",new_user_registration_path %></li>
          <li><%= link_to "-ログイン",new_user_session_path %></li>
        </ul>
      </div>
    </div>
    <%= link_to("/") do %>
      <div class="logo logo2">
        <%= image_tag "logo.png", class:"logo_ti" %>
      </div>
    <% end %>
  </div>
</footer>

app/views/shared/_header.html.erb
<header class="input_box_body">
  <div class="he">
    <%= link_to("/") do %>
      <div class="logo">
        <%= image_tag "logo.png", class:"logo_ti" %>
      </div>
    <% end %>
    <%= form_with(url: search_recipes_path, local: true, method: :get, class: "search-form") do |f| %>
      <div class="input-box">
      <%= f.text_field :keyword, placeholder:'キーワードから探す', class:"seach_text" %>
      </div>
      <%= f.submit "検索", class: "search-btn" %>
    <% end %>
    <div class="header_if">
      <% if user_signed_in? %>
      <%= link_to "/users/#{current_user.id}/mypege/" do %>
      <div class="rgou">
            <p>マイページ</p>
          </div>
      <% end %>
        <%= link_to(notifications_path,method: :get) do %>
          <% if unchecked_notifications.any? %>
          <div class="tsuchi">
            <span class="fa-layers fa-fw">
              <span class="fas fa-bell"></span>
              <span class="fas fa-circle"></span>
            </span>
          </div>
          <% else %>
          <div class="tsuchi">
              <i class="fas fa-bell"></i>
          </div>
          <% end %>
        <% end %>
        <%= link_to(destroy_user_session_path,method: :delete) do %>
          <div class="rgout">
            <p>ログアウト</p>
          </div>
        <% end %>
        <% else %>
        <%=link_to(new_user_registration_path) do %>
          <div class="kinto">
            <p>会員登録</p>
          </div>
        <% end %>
        <%= link_to(new_user_session_path) do %>
          <div class="rgin">
            <p>ログイン</p>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</header>